// Auto-generated by scripts/build-kb.js — DO NOT EDIT
export const embeddedChunks = [
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "B+H 2.0 架构",
    "content": "# B+H 2.0 架构"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "",
    "content": "B+H 指 BVI 控股公司加香港运营或银行账户。BVI 做控股、隔离和资产持有；香港做运营、银行账户、交易执行、合规申报和外部商业界面。"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "架构层次",
    "content": "## 架构层次"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "架构层次",
    "content": "典型架构是家族成员或信托控制 BVI 公司，BVI 公司作为控股层持有香港公司，香港公司作为运营层连接银行账户、投资交易和全球资产配置。"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "BVI 的作用",
    "content": "## BVI 的作用"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "BVI 的作用",
    "content": "BVI 适合做资产持有、股权隔离、家族控制、VISTA 信托连接和跨境架构控股层。它不是主要运营实体，也不是银行账户便利性的核心来源。"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "香港的作用",
    "content": "## 香港的作用"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "香港的作用",
    "content": "香港适合做银行账户、多币种收付、投资交易、税务申报、商业运营和外部合同界面。B+H 组合的优势来自控股层与运营层分离。"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "适用场景",
    "content": "## 适用场景"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "适用场景",
    "content": "B+H 适合家办、财富保全、跨境资产配置、非上市控股和需要香港银行关系的用户。不适合作为单纯上市架构；拟上市企业通常需要另外考虑开曼、港股规则和中国备案要求。"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "合规要点",
    "content": "## 合规要点"
  },
  {
    "source": "B+H 2.0 架构",
    "url": "https://bvi.vg/bvi-2-0/b-plus-h/",
    "heading": "合规要点",
    "content": "BVI 公司需要完成 UBO 申报、年度维护和 FAR 年度财务申报。香港公司需要正常年审、报税和维护银行 KYC。涉及境内资金出境时，需要关注 ODI、37 号文和外汇路径。"
  },
  {
    "source": "BVI 2.0 总纲",
    "url": "https://bvi.vg/bvi-2-0/",
    "heading": "BVI 2.0 总纲",
    "content": "# BVI 2.0 总纲"
  },
  {
    "source": "BVI 2.0 总纲",
    "url": "https://bvi.vg/bvi-2-0/",
    "heading": "",
    "content": "BVI 2.0 指的是合规时代的 BVI。它不再以“藏钱”为核心叙事，而是以“留钱”、资产保护、合规持有、权属隔离和跨境家办架构为核心价值。"
  },
  {
    "source": "BVI 2.0 总纲",
    "url": "https://bvi.vg/bvi-2-0/",
    "heading": "核心判断",
    "content": "## 核心判断"
  },
  {
    "source": "BVI 2.0 总纲",
    "url": "https://bvi.vg/bvi-2-0/",
    "heading": "核心判断",
    "content": "BVI 没有死，BVI 进化了。在 CRS、UBO、经济实质和银行 KYC 越来越透明的环境下，BVI 的价值从“不被看见”升级为“被看见也拿不走”。"
  },
  {
    "source": "BVI 2.0 总纲",
    "url": "https://bvi.vg/bvi-2-0/",
    "heading": "BVI 1.0 与 BVI 2.0",
    "content": "## BVI 1.0 与 BVI 2.0"
  },
  {
    "source": "BVI 2.0 总纲",
    "url": "https://bvi.vg/bvi-2-0/",
    "heading": "BVI 1.0 与 BVI 2.0",
    "content": "BVI 1.0 的旧认知是藏钱、避税、绝对保密、灰色资金和不被看见。BVI 2.0 的新事实是资产保护、合规持有、CRS 申报、UBO 备案、合法合规的家族财富和被看见也拿不走。"
  },
  {
    "source": "BVI 2.0 总纲",
    "url": "https://bvi.vg/bvi-2-0/",
    "heading": "四大支柱",
    "content": "## 四大支柱"
  },
  {
    "source": "BVI 2.0 总纲",
    "url": "https://bvi.vg/bvi-2-0/",
    "heading": "四大支柱",
    "content": "BVI 2.0 的核心内容包括法规更新追踪、CRS 2.0 专题、B+H 2.0 架构、常见误读澄清，以及与中国法律衔接。"
  },
  {
    "source": "BVI 2.0 总纲",
    "url": "https://bvi.vg/bvi-2-0/",
    "heading": "合规时代的定位",
    "content": "## 合规时代的定位"
  },
  {
    "source": "BVI 2.0 总纲",
    "url": "https://bvi.vg/bvi-2-0/",
    "heading": "合规时代的定位",
    "content": "CRS 2.0 对合法商人几乎没有影响。真正的风险不是透明，而是资金来源、税务居民身份、最终受益人登记、银行 KYC 和申报口径之间不一致。"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "与中国法律衔接",
    "content": "# 与中国法律衔接"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "",
    "content": "BVI 架构与中国法律不是对立的。合规的 BVI 架构可以在中国外汇、税务和跨境信息交换框架下正常运行。"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "核心判断",
    "content": "## 核心判断"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "核心判断",
    "content": "关键不是有没有 BVI，而是资金、税务、身份和备案是否一致。BVI 2.0 时代，中国用户面对的主要问题是能不能把境内出境路径、税务居民身份、最终受益人登记、CRS 信息交换和银行 KYC 形成一致闭环。"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "外汇管理",
    "content": "## 外汇管理"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "外汇管理",
    "content": "企业出境投资通常需要关注 ODI 备案。个人特殊目的公司安排通常需要关注 37 号文登记。未备案资金出境在 CRS 信息交换后更容易形成解释压力和信息不一致风险。"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "中国税务",
    "content": "## 中国税务"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "中国税务",
    "content": "BVI 公司本身是境外法人，但中国居民股东、实际控制人、资金来源和管理决策可能把中国税务规则带入架构判断。CFC 规则关注中国居民通过低税地区受控实体累积利润、延迟纳税的安排。"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "CRS 信息交换后的关注点",
    "content": "## CRS 信息交换后的关注点"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "CRS 信息交换后的关注点",
    "content": "税务机关通常关注是否完税、是否备案、是否有逃税嫌疑、资金来源是否清晰、账户信息和税务居民身份是否一致。CRS 信息交换本身不是稽查结论。"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "合规底线",
    "content": "## 合规底线"
  },
  {
    "source": "与中国法律衔接",
    "url": "https://bvi.vg/bvi-2-0/china-connection/",
    "heading": "合规底线",
    "content": "中国法律衔接的核心不是回避监管，而是让 BVI 架构在中国外汇、税务和 CRS 信息交换框架下形成可解释、可证明、可维护的闭环。"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "CRS 2.0 专题",
    "content": "# CRS 2.0 专题"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "",
    "content": "CRS 2.0 是共同汇报标准的升级版，不是新税种，不是全球征税，也不是自动补税。它的核心是扩大金融账户和控制人信息交换的范围。"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "三大升级",
    "content": "## 三大升级"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "三大升级",
    "content": "CRS 2.0 的重点包括加密资产纳入报告范围、双重身份不能择一申报、多层架构穿透至实际控制人。"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "对合法商人的影响",
    "content": "## 对合法商人的影响"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "对合法商人的影响",
    "content": "对合法商人而言，CRS 2.0 的影响通常是信息一致性要求提高，而不是自动产生税负。已经完税、资金来源清晰、身份和账户申报一致的用户，核心风险较低。"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "常见恐慌点",
    "content": "## 常见恐慌点"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "常见恐慌点",
    "content": "“BVI 公司要被查了”并不准确。信息交换不等于税务稽查。税务机关取得信息后，是否进一步处理取决于是否存在逃税、漏税、申报不一致或资金来源不清等线索。"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "",
    "content": "“我要补税了”也不准确。CRS 2.0 本身不创造新的税种，也不自动产生补税义务。"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "BVI 公司 CRS 合规清单",
    "content": "## BVI 公司 CRS 合规清单"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "BVI 公司 CRS 合规清单",
    "content": "确认 BVI 公司的税务居民身份。确认相关申报口径一致。确保 UBO 信息已通过注册代理备案。如持有加密资产，确认托管平台和账户申报安排。"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "信托与穿透",
    "content": "## 信托与穿透"
  },
  {
    "source": "CRS 2.0 专题",
    "url": "https://bvi.vg/bvi-2-0/crs-2/",
    "heading": "信托与穿透",
    "content": "CRS 框架下，金融机构通常需要识别信托相关的委托人、受托人、保护人、受益人及实际控制人。穿透识别用于税务信息交换，不等于信托资产隔离功能失效。"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "官方来源",
    "content": "# 官方来源"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "",
    "content": "涉及 BVI、香港、中国内地和国际监管的信息，应优先从官方机构核验。搜索引擎结果中可能混有广告站、代理站或仿冒页面。"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "BVI 官方机构",
    "content": "## BVI 官方机构"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "BVI 官方机构",
    "content": "BVI Financial Services Commission 负责金融服务监管、公司注册、注册代理人、受监管实体、受益所有权和金融服务法规。"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "",
    "content": "BVI International Tax Authority 负责 CRS、FATCA、经济实质、CbCR 和国际税务信息交换。"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "",
    "content": "BVI Government 是 BVI 政府公告、公共政策、政府部门和官方新闻入口。"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "香港相关机构",
    "content": "## 香港相关机构"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "香港相关机构",
    "content": "香港公司注册处负责香港公司注册、周年申报、公司查册和公司注册资料。香港税务局负责香港税务、商业登记和税务资料。香港金融管理局负责银行体系和金融监管。香港证监会负责证券、期货、资产管理和持牌机构监管。"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "中国内地相关机构",
    "content": "## 中国内地相关机构"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "中国内地相关机构",
    "content": "国家税务总局用于核验中国税收政策和税务公告。国家外汇管理局用于核验外汇管理、资本项目和跨境资金流动政策。国家发改委和商务部用于核验 ODI 和境外投资政策。中国证监会用于核验境外上市备案和证券监管资料。"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "国际组织",
    "content": "## 国际组织"
  },
  {
    "source": "官方来源",
    "url": "https://bvi.vg/bvi-2-0/sources/",
    "heading": "国际组织",
    "content": "OECD 用于核验 CRS、CARF 和国际税务透明标准。FATF 用于核验反洗钱和加强监控司法管辖区名单。EU Council 用于核验欧盟税务非合作司法管辖区名单。"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "UBO 与常见误读",
    "content": "# UBO 与常见误读"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "",
    "content": "BVI 信息透明不等于全部公开。UBO 申报主要是向注册代理和监管体系备案，不等于任何公众都能随意查到完整资料。"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "BVI 不能用了的误读",
    "content": "## BVI 不能用了的误读"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "BVI 不能用了的误读",
    "content": "CRS 交换的是信息，不改变税收规则，也不直接否定 BVI 的资产隔离功能。BVI 的价值在于权属隔离、控股安排、信托工具和普通法框架。"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "BVI 信息全部公开的误读",
    "content": "## BVI 信息全部公开的误读"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "BVI 信息全部公开的误读",
    "content": "第三方查询通常需要满足门槛、正当利益证明、审查程序和信息范围限制。查询不是公开查册，也不等于地址、证件、完整资产信息全部公开。"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "FATF 灰名单的误读",
    "content": "## FATF 灰名单的误读"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "FATF 灰名单的误读",
    "content": "灰名单代表加强监控，不等于黑名单，也不等于银行全面拒绝 BVI 公司。合规客户会面对更严格 KYC，需要准备资金来源、业务说明、架构图、UBO 和税务居民身份资料。"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "经济实质的误读",
    "content": "## 经济实质的误读"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "经济实质的误读",
    "content": "BVI 对纯控股公司通常适用较轻经济实质要求。多数家办 BVI 公司如果定位为纯控股公司，重点是确认活动类别、保存记录、完成申报和年度维护。"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "BVI 信托穿透的误读",
    "content": "## BVI 信托穿透的误读"
  },
  {
    "source": "UBO 与常见误读",
    "url": "https://bvi.vg/bvi-2-0/myths/",
    "heading": "BVI 信托穿透的误读",
    "content": "CRS 穿透识别信托相关人士是税务信息交换要求，不等于信托资产隔离功能消失。信托保护功能仍取决于信托文件、适用法律、资产转移有效性和具体事实。"
  }
] as const;
