import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.join(__dirname, '..');
const KB_DIR = path.join(ROOT, 'knowledge-base');
const OUTPUT_DIR = path.join(ROOT, 'functions', '_generated');
const OUTPUT = path.join(OUTPUT_DIR, 'kb-embedded.ts');

function ensureOutputDir() {
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }
}

function parseFrontmatter(content, file) {
  const fallbackTitle = file.replace(/\.md$/, '').replace(/-/g, ' ');
  const meta = { title: fallbackTitle, url: '' };
  let body = content;

  if (content.startsWith('---')) {
    const end = content.indexOf('\n---', 3);
    if (end !== -1) {
      const frontmatter = content.slice(3, end).trim();
      body = content.slice(end + 4).trim();
      for (const line of frontmatter.split('\n')) {
        const [rawKey, ...rawValue] = line.split(':');
        const key = rawKey?.trim();
        const value = rawValue.join(':').trim().replace(/^['"]|['"]$/g, '');
        if (key === 'title' && value) meta.title = value;
        if (key === 'url' && value) meta.url = value;
      }
    }
  }

  const h1 = body.match(/^#\s+(.+)$/m);
  if (h1?.[1] && meta.title === fallbackTitle) {
    meta.title = h1[1].trim();
  }

  return { meta, body };
}

function chunkMarkdown(body) {
  const normalized = body.replace(/\r\n/g, '\n').trim();
  const blocks = normalized.split(/\n\s*\n+/).map((block) => block.trim()).filter(Boolean);
  const chunks = [];
  let currentHeading = '';

  for (const block of blocks) {
    const heading = block.match(/^#{1,3}\s+(.+)$/m);
    if (heading?.[1]) currentHeading = heading[1].trim();

    if (block.length < 24) continue;
    chunks.push({ heading: currentHeading, content: block.slice(0, 1800) });
  }

  return chunks;
}

ensureOutputDir();

if (!fs.existsSync(KB_DIR)) {
  fs.writeFileSync(OUTPUT, 'export const embeddedChunks = [] as const;\n', 'utf-8');
  console.warn('[build-kb] knowledge-base not found, empty KB');
  process.exit(0);
}

const files = fs.readdirSync(KB_DIR).filter((file) => file.endsWith('.md')).sort();
const embeddedChunks = [];

for (const file of files) {
  const raw = fs.readFileSync(path.join(KB_DIR, file), 'utf-8');
  const { meta, body } = parseFrontmatter(raw, file);
  const chunks = chunkMarkdown(body);

  for (const chunk of chunks) {
    embeddedChunks.push({
      source: meta.title,
      url: meta.url,
      heading: chunk.heading,
      content: chunk.content,
    });
  }
}

const output = `// Auto-generated by scripts/build-kb.js — DO NOT EDIT\nexport const embeddedChunks = ${JSON.stringify(embeddedChunks, null, 2)} as const;\n`;
fs.writeFileSync(OUTPUT, output, 'utf-8');
console.log(`[build-kb] ${embeddedChunks.length} chunks from ${files.length} files`);
